adx_authenticationrequired: false
adx_editexistingrecordpermitted: true
adx_multiplerecordsperuserpermitted: false
adx_name: VHA Health Care Talent Academy Application
adx_progressindicatorenabled: true
adx_progressindicatorignorelaststep: false
adx_progressindicatorposition: 756150000
adx_progressindicatorprependstepnum: false
adx_progressindicatortype: 756150000
adx_savechangeswarningonclose: false
adx_startnewsessiononload: true
adx_startstep: f0855e6a-e5cd-eb11-bacc-001dd801ccff
adx_webformid: f264f667-13b8-eb11-8236-001dd8021d55
