import { BaseForm } from "./BaseForm";

export namespace CDCEP {
    //IMPORTANT: Do not name your class with the same name that is generated by the Typings!
    // For example, for the Account table/entity, you may use `AccountForm` as the class name
    // since the typings will be generated with the name `Account`.
    export class TestForm extends BaseForm {
        public async OnLoad(eventContext: Xrm.Events.EventContext): Promise<void> {
            super.OnLoad(eventContext);
            //Write your code here
            this.log("TestForm OnLoad", eventContext);
        }
    }
}

window.CDCEP.Forms.YourFormName = window.CDCEP.Forms.YourFormName || new CDCEP.TestForm();