adx_displayorder: 36
adx_enablerating: false
adx_enabletracking: false
adx_excludefromsearch: false
adx_feedbackpolicy: 756150000
adx_hiddenfromsitemap: false
adx_isroot: false
adx_name: VHA Health Care Talent Academy
adx_pagetemplateid: ea3ac207-d6b7-eb11-8236-001dd8021d55
adx_parentpageid: 394d2396-7be6-4ee0-bf79-527c8962c7cc
adx_partialurl: vha_healthcareacademy
adx_publishingstateid: ed67356b-a2db-49a9-b26d-4c8a59e3d9a7
adx_rootwebpageid: 4f4bae48-d6b7-eb11-8236-001dd8021d55
adx_sharedpageconfiguration: true
adx_webform: f264f667-13b8-eb11-8236-001dd8021d55
adx_webpageid: 534bae48-d6b7-eb11-8236-001dd8021d55
adx_webpagelanguageid: e9e755c4-c26a-e611-80d7-00155d889a88
