adx_isdefault: false
adx_name: getapplicationinvitationbycode-json
adx_pagetemplateid: 0b42d10e-f2fa-eb11-94ef-001dd8301ca5
adx_type: 756150001
adx_usewebsiteheaderandfooter: false
adx_webtemplateid: deb19cf6-f1fa-eb11-94ef-001dd8301ca5
